version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blockchain
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  indexer:
    build: ./.
    container_name: indexer
    environment:
      - CONFIG_PATH=/app/config/config.toml
    volumes:
      - ./config:/app/config
    depends_on:
      - postgres
    command: ["/bin/bash", "-c", " /app/indexer"]

  server:
    build: ./.
    container_name: server
    environment:
      - CONFIG_PATH=/app/config/config.toml
    volumes:
       - ./config:/app/config
    ports:
      - "30303:30303"
    depends_on:
      - postgres
      - indexer
    command: ["/bin/bash", "-c", "/app/server"]
