chain_name = "shielded-expedition"

[database]
host = "postgres"
port = "5432"
user = "postgres"
password = "1234"
db_name = "blockchain"
# Optional field to configure a timeout if database connection 
# fails.
connection_timeout = 20
create_index = true

[server]
port = "30303"

[indexer]
rpc = "http://127.0.0.1:26657"
wait_for_block = 10
max_blocks_in_channel = 100

[prometheus]
host = "0.0.0.0"
port = "9000"
